apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-21T12:35:32Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "71842"
  uid: f7e960a5-9238-4b67-8e16-f3ca0a05b5a2
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-f78pw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-f78pw
    secret:
      defaultMode: 420
      secretName: default-token-f78pw
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T12:35:32Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T12:35:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T12:35:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-21T12:35:32Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d5e6de2c234693cb1d0d4c16636f53dcb92692470ce00f45ba81ba5a24f539d8
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:df13abe416e37eb3db4722840dd479b00ba193ac6606e7902331dcea50f4f1f2
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-21T12:35:35Z"
  hostIP: 192.168.99.101
  phase: Running
  podIP: 172.17.0.4
  podIPs:
  - ip: 172.17.0.4
  qosClass: BestEffort
  startTime: "2021-05-21T12:35:32Z"
