apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gigi
  name: gigi
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
