apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: train-schedule
  name: train-schedule
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train-schedule
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: train-schedule
    spec:
      containers:
      - image: dzhovid/train-schedule:v1
        name: train-schedule
        ports:
        - containerPort: 8080
        resources: {}
status: {}
